name: test

on:
  push:
  pull_request:
  schedule:
    - cron: '30 10 * * *'

jobs:
  test:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    strategy:
      matrix:
        ruby: [ 'head', '3.0', '2.7', '2.6' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake
    - id: build
      run: |
        rake build
        echo "::set-output name=pkg::${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}"
      env:
        RUNNING_OS: ${{matrix.os}}
      if: "matrix.ruby == '3.0'"
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: steps.build.outputs.pkg
