name: test

on:
  push:
  pull_request:
  schedule:
    - cron: '25 10 * * *'

jobs:
  test:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'head', '3.0', '2.7', '2.6' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - { os: ubuntu-latest, ruby: jruby-head }
          - { os: ubuntu-latest, ruby: jruby-9.2 }
          - { os: ubuntu-latest, ruby: truffleruby }
          - { os: ubuntu-latest, ruby: truffleruby-head }
    runs-on: ${{ matrix.os }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
    - if: ${{ matrix.ruby == '3.0' }}
      run: gem install bundler
    - run: gem update --system
    - name: Run test
      run: bundle exec rake
    - id: build
      run: |
        bundle exec rake build
        echo "::set-output name=pkg::${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}"
      env:
        RUNNING_OS: ${{matrix.os}}
      if: "matrix.ruby == '3.0'"
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: steps.build.outputs.pkg
